### ISSUE TITLE
Not working on Mac OS X

### ISSUE THREAD

**Issue by koba-e964** [kw-udon/constexpr-8cc#1]
`run_8cc.py` stops running while calling `sed`.

(Although `g++` is an alias of `clang++` in my machine, I believe it doesn't matter because `g++` is never called.)
Output:
 ```
$ ./run_8cc.py x86 ./test/hello.c -o ./hello.exe
INFO: Start compilation from "./test/hello.c" to "./hello.exe"
INFO: Convert C program into C++ string literal
cp ./test/hello.c ./test/hello.c.txt
sed -i 1iR\\\"( ./test/hello.c.txt
sed: 1: "./test/hello.c.txt": invalid command code .
```

**Comment by koba-e964** [comment]
I found a workaround of this problem:
by replacing https://github.com/kw-udon/constexpr-8cc/blob/f19c6adc553eb8c47cadce28d942fc95d652b671/run_8cc.py#L83-L85 in `run_8cc.py` with

```
call('sed', '-i', '', '1s/^/R\\"(/',  infile_txt)
call('sed', '-i', '', '$s/$/)\"/',  infile_txt)
call('sed', '-i', '', 's/EIGHT_CC_INPUT_FILE .*/EIGHT_CC_INPUT_FILE   \\"{}\\"/'
```

`sed` worked correctly and `g++` started.
I think other invocations of `sed` should be replaced in the same way (at least you are trying to run it on MacOS X).

I'm not sure if this fix works on Linux.

**Comment by keiichiw** [comment]
@koba-e964 
Thank you for reporting!
I think this problem was fixed by #3.

Could you try in your environment?
If an error still occurs, please reopen this issue.

**Comment by keiichiw** [comment]
Now, tests on OS X are performed by Travis CI.

**Comment by koba-e964** [comment]
It works on Mac OS! Thanks!
